### ISSUE TITLE
3D analysis terribly slow

### ISSUE THREAD

**Issue by maryebrown1** [hansenjn/MotiQ#2]
The 3D analysis of a Z-stack took over three hours! Is this typical? I have a Windows 11 laptop with 64GB RAM and a 16 GB GPU.

On a different computer, I'm getting the following error message when I try to run MotiQ Cropper:

`(Fiji Is Just) ImageJ 2.9.0/1.54a16; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 539MB of 48948MB (1%)
 
java.lang.NullPointerException
	at motiQ_cr.Cropper_.run(Cropper_.java:110)
	at ij.IJ.runUserPlugIn(IJ.java:239)
	at ij.IJ.runPlugIn(IJ.java:205)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)

`
I'm not sure how to interpret this error message. Can someone please tell me what is wrong and how do I rectify it? Thank you very much.
Mary

**Comment by maryebrown1** [comment]
MotiQ Cropper is suddenly working, but now I get the error message below when I try to MotiQ Thresholder. I have no coding experience and I do not know how to interpret the error message. Can someone tell me what is wrong and how do I rectify it? Thank you.
``(Fiji Is Just) ImageJ 2.9.0/1.53v; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 276MB of 48948MB (<1%)
 
java.lang.NullPointerException
	at motiQ_thr.Thresholder.run(Thresholder.java:393)
	at ij.IJ.runUserPlugIn(IJ.java:239)
	at ij.IJ.runPlugIn(IJ.java:205)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)

**Comment by hansenjn** [comment]
Hi Mary,

I am very sorry for my very late reply - I somehow overlooked your messages, sorry!

As for your MotiQ Cropper error message: This message is thrown when you are processing an image that is not saved. MotiQ cropper saves the output image at the file directory where the image was stored that you are processing. If you however are cropping an image that in FIJI exists in a non-saved state FIJI cannot find the file position and then MotiQ cropper does not know where to store the file and thus, crashes.
I agree however that this is very cryptic and will work on a pop up error message that informs you about this issue when you run MotiQ cropper on an unsaved image so it is understandable.

As for the MotiQ Thresholder message: This message is thrown when MotiQ Thresholder cannot find the source file from which you cropped the files in MotiQ Cropper. MotiQ Thresholder uses the original file from which images were cropped with MotiQ Cropper to determine an intensity threshold. It searches for this original file in the same folder as where the input image is stored. If it cannot find the file, it crashes.
Also here, I understand that this is cryptic, and I will introduce a notification explaining the error in more detail.
You fix this error by making sure that the Cropped file and the file from which it was cropped are in the same folder.

Now for the time span: The 3D analysis time largely depends on the dimensions of your image and the number of "positive" pixels in your image. If you are running a whole z-stacks with many cells and with many e.g. noise particles that need to be filtered, this can go up to hours, yes. Note that MotiQ is not parallelized which is why it does not run anything in parallel and can be slow for large images. However, I am also aware of that running MotiQ 3D in FIJI is sometimes much slower than running it in a pure ImageJ, which is not explainable and not related to MotiQ but to differences between FIJI and ImageJ.

I hope this helps you and even though I reply so terribly late! I will now introduce the changes to make the errors more understandable.

Best
Jan

**Comment by hansenjn** [comment]
Update - The latest release of plugins has now inbuilt that these errors are output in an understandable format:
https://github.com/hansenjn/MotiQ/releases/tag/v0.2.0

**Comment by maryebrown1** [comment]
Thank you, Jan! I have the plugin working smoothly now!

**Comment by hansenjn** [comment]
Thank you! Happy to hear that!

**Comment by maryebrown1** [comment]
I have a client who wants to measure soma size with some morphometric
measurements, so I had to resort to Imaris for these statistics. In future
versions, segmenting the soma and measuring its area or volume would be
very helpful. Thank you, Jan!

**Comment by hansenjn** [comment]
Thank you for the feedback! I agree and yes it is on the list - just need to find the time to implement it!
Best
Jan
